### ISSUE TITLE
Use cudatoolkit value for activation script

### ISSUE THREAD

**Issue by bnemanich** [open-ce/nvcc-feedstock#2]
Currently, the activation script looks for CUDA in a directory that assumes CUDA is at version 10.2. This should be changed to use the value from cudatoolkit.

**Comment by jayfurmanek** [comment]
The activation script first looks in CUDA_HOME for the location:
https://github.com/open-ce/nvcc-feedstock/blob/master/scripts/activate.sh#L16

failing that, it then checks some standard locations:
```
/usr/local/cuda
/usr/local/cuda-10.2
```

I figure we can add `/usr/local/cuda-11` to that list once we support that.

**Comment by jayfurmanek** [comment]
And remember this package needs to know about the system installed CUDA Toolkit because the `cudatoolkit` package from Defaults doesn't have the compilers.

**Comment by jayfurmanek** [comment]
ah, you mean `{cudatoolkit}`
https://github.com/open-ce/open-ce/blob/master/conda_build_config.yaml#L30-L31

This will take a bit of custom parsing and replacement at build time.

**Comment by cdeepali** [comment]
Shall we replace `10.2` in `activate.sh` script with some string like `CUDA_REQ_VERSION` and then do the parsing and replace at build time.

**Comment by bnemanich** [comment]
Yes, I think we need to look at the value in  `{cudatoolkit}`. We should probably also throw an error if the CUDA that it finds is a different version than what is specified in `{cudatoolkit}`.

**Comment by cdeepali** [comment]
Yes we do have one at build time - https://github.com/open-ce/nvcc-feedstock/blob/master/recipe/install_nvcc.sh#L36

and during activate too - https://github.com/open-ce/nvcc-feedstock/blob/master/scripts/activate.sh#L29
